#!/usr/bin/env node
// Parses packages/miksin-ui/src/base.css and generates apps/docs/src/generated/tokens.ts
import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')

const css = readFileSync(resolve(ROOT, 'packages/miksin-ui/src/base.css'), 'utf8')
const descriptions = JSON.parse(
  readFileSync(resolve(ROOT, 'apps/docs/src/data/token-descriptions.json'), 'utf8')
)

function parseTokenLines(block) {
  const tokens = []
  for (const line of block.split('\n')) {
    const m = line.match(/^\s*(--[\w-]+)\s*:\s*([^;]+?)\s*;/)
    if (m) tokens.push({ name: m[1], value: m[2].trim() })
  }
  return tokens
}

// Parse :root into sections delimited by /* Primitive */ /* Semantic */ /* Component */
const rootMatch = css.match(/:root\s*\{([\s\S]*?)\}/)
if (!rootMatch) { console.error('ERROR: :root block not found in base.css'); process.exit(1) }

const sections = { primitive: [], semantic: [], component: [] }
let current = null
for (const line of rootMatch[1].split('\n')) {
  const sectionMatch = line.match(/\/\*\s*(Primitive|Semantic|Component)\s*\*\//)
  if (sectionMatch) { current = sectionMatch[1].toLowerCase(); continue }
  if (!current) continue
  const m = line.match(/^\s*(--[\w-]+)\s*:\s*([^;]+?)\s*;/)
  if (m) sections[current].push({ name: m[1], value: m[2].trim() })
}

// Parse [data-theme="dark"] block
const darkMatch = css.match(/\[data-theme="dark"\]\s*\{([\s\S]*?)\}/)
const darkTokens = darkMatch ? parseTokenLines(darkMatch[1]) : []

function withDesc(tokens) {
  return tokens.map(t => ({ ...t, description: descriptions[t.name] ?? '' }))
}

const out = `// AUTO-GENERATED by tools/generate-tokens.mjs — do not edit manually
// Re-run via: node tools/generate-tokens.mjs  (or pnpm --filter docs build)

export interface Token { name: string; value: string; description: string }
export interface DarkToken { name: string; value: string }

export const primitive: Token[] = ${JSON.stringify(withDesc(sections.primitive), null, 2)}

export const semantic: Token[] = ${JSON.stringify(withDesc(sections.semantic), null, 2)}

export const component: Token[] = ${JSON.stringify(withDesc(sections.component), null, 2)}

export const darkOverrides: DarkToken[] = ${JSON.stringify(darkTokens, null, 2)}
`

mkdirSync(resolve(ROOT, 'apps/docs/src/generated'), { recursive: true })
writeFileSync(resolve(ROOT, 'apps/docs/src/generated/tokens.ts'), out)
console.log('✓ Generated apps/docs/src/generated/tokens.ts')
